name: Mirror Upbit Materials (hot, single-file + 10 shards)
on:
  workflow_dispatch:
  push: { branches: [ main ] }
permissions: { contents: write }
jobs:
  mirror-hot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # (여기에 원래 LLM_MATERIALS.json 생성 스텝이 있어야 합니다)
      - name: Setup Python
        run: python3 -V
      - name: Split LLM_MATERIALS.json into 10 shards (materials_10/)
        run: python3 scripts/split_llm_materials.py
      - name: Commit and push shards
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add materials_10/*.json || true
          if ! git diff --cached --quiet; then
            git commit -m "chore(hot): update materials shards (10)"
            git push
            echo "::notice title=Commit::Pushed materials_10 shards"
          else
            echo "::notice title=Commit::No shard changes"
          fi
