name: mirror-to-gist
on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - LLM_MATERIALS.json
  schedule:
    - cron: "*/15 * * * *"
permissions:
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Prepare source
        run: |
          set -euo pipefail
          if [ -s LLM_MATERIALS.json ]; then
            if jq -c . LLM_MATERIALS.json > LLM_MATERIALS.min.json 2>/dev/null; then
              SRC="LLM_MATERIALS.min.json"
            else
              echo "::error::LLM_MATERIALS.json is not valid JSON"; exit 1
            fi
          else
            echo "::error::LLM_MATERIALS.json not found"; exit 1
          fi
          echo "SRC=$SRC" >> $GITHUB_ENV
      - name: Build Gist payload
        run: |
          set -euo pipefail
          jq -n --rawfile content "$SRC" \
            '{files: {"LLM_MATERIALS.json": {content: $content}}}' > payload.json
          wc -c payload.json
      - name: PATCH Gist
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: |
          set -euo pipefail
          curl -sS -X PATCH \
            -H "Authorization: token ${GIST_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/gists/${GIST_ID}" \
            --data @payload.json | jq -r '.updated_at, .html_url'
