name: Mirror Upbit Materials (5min, chunked)

on:
  schedule:
    - cron: "*/5 * * * *"   # 5분마다 (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    env:
      BASE: "https://api.shenqn.uk"
      CHUNK: "30"
      UA: "GA-mirror/1.0"
    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Build KRW market list (from Upbit public API)
        run: |
          set -euo pipefail
          curl -4fsSL "https://api.upbit.com/v1/market/all?isDetails=false" \
            -H "User-Agent: $UA" \
          | jq -r '.[].market' | grep '^KRW-' > markets.txt
          echo "Total markets: $(wc -l < markets.txt)"

      - name: Fetch materials in chunks
        run: |
          set -euo pipefail
          rm -rf parts && mkdir -p parts
          mapfile -t ARR < markets.txt
          i=0; n=${#ARR[@]}
          while [ $i -lt $n ]; do
            part=$(IFS=,; echo "${ARR[@]:i:CHUNK}")
            out="parts/part_$((i/CHUNK+1)).json"
            # 지수 백오프 재시도
            for d in 0 0.6 1.0 1.7 3.0 5.0; do
              sleep "$d"
              url="${BASE}/materials.json?mode=selected&full=1&markets=${part}"
              code=$(curl -4sS -w "%{http_code}" -o "$out" -H "User-Agent: $UA" "$url" || true)
              if [ "$code" = "200" ]; then
                echo "OK: $out"
                break
              else
                echo "HTTP $code → retry"
                rm -f "$out"
              fi
            done
            if [ ! -s "$out" ]; then
              echo "FAILED: $out" >&2
              exit 1
            fi
            i=$((i+CHUNK))
          done

      - name: Merge parts → LLM_MATERIALS.json
        run: |
          set -euo pipefail
          jq -s '
            def M: [.[].markets[]];
            {
              version:    (.[0].version // "LLM_MATERIALS_V1"),
              timestamps: (.[0].timestamps // {kst:"",utc:""}),
              meta: (
                (.[0].meta // {}) as $m
                | $m.params = ($m.params // {})
                | $m.params.markets = (M | map(.market) | unique)
                | $m
              ),
              markets: (M | unique_by(.market))
            }' parts/part_*.json > LLM_MATERIALS.json
          ls -lh LLM_MATERIALS.json
          head -c 200 LLM_MATERIALS.json || true

      - name: Commit if changed
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add LLM_MATERIALS.json || true
          if git diff --cached --quiet; then
            echo "No changes"; exit 0
          fi
          git commit -m "Update materials (chunked) $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git push
