name: Render Materials Snapshot

on:
  workflow_dispatch:
  push:
    paths:
      - LLM_MATERIALS.json
      - scripts/render_snapshot.sh
  schedule:
    - cron: "*/5 * * * *"

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Render static snapshot
        run: bash scripts/render_snapshot.sh
      - name: Commit if changed
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet -- docs/materials.html docs/LLM_MATERIALS.pretty.json; then
            git add docs/materials.html docs/LLM_MATERIALS.pretty.json
            git commit -m "chore(snapshot): refresh static HTML"
            git push
          else
            echo "No changes to commit"
          fi
